#' Expected LR for pairwise inbred relationship
#'
#' The expected value of  LR = P(data|HP)/P(data|HD=unrelated)
#' is calculated assuming that the data is generated by HT.
#'
#' @param p Double vector, allele frequencies
#' @param deltaHP Jacquard cofficients under HP, row vector, length 9
#' @param deltaHT Jacquard cofficients under HT, row vector, length 9
#'
#' @details The approach of the inbred.pdf note is implemented
#' @return The expected value of LR
#' @export
#' @examples
#' # HP: 9, whose parents are first cousins, is father of 11
#' # HD: 9 and 11 are unrelated
#' # HP = HT
#' # We first find deltaHP
#' require(ribd)
#' x1 = pedtools::cousinPed(1, child = TRUE)
#' x1 = pedtools::addSon(x1, parent = 9)
#' deltaHP = matrix(ribd::jacquard(x1, c(9,11)), nrow=1)
#' p = c(0.2, 0.8)
#' mu = ELRH(p, deltaHP)
#' # Next we confirm using Eq (1.2) of the note
#' f = inbreeding(x1)[9]
#' L = length(p)
#' s = sum(1/p)
#' mu.eq = (0.5*s-(L+1)/4)*f^2+(L-1)/2*f+(L+3)/4
#' stopifnot(mu == mu.eq)
#'
ELRH <- function(p, deltaHP, deltaHT = deltaHP){
  # Eq (1.3) in note:
  deltaHP%*%LRH(p)%*%t(deltaHT)
}

